<#
.SYNOPSIS
    Pica Manga Development Startup Script
    优雅地启动开发环境：清理旧进程 -> 检查环境 -> 启动服务

.DESCRIPTION
    此脚本用于启动 Pica Manga 的开发环境。
    它会自动执行以下操作：
    1. 检查并终止占用端口 (3000, 5173) 的旧进程。
    2. 检查 .env 文件是否存在，不存在则从 .env.example 创建，并自动配置局域网IP。
    3. 获取并显示本机局域网 IP 地址，方便手机访问。
    4. 使用 concurrently 并行启动前端 (Vite) 和后端 (Nodemon)。

.EXAMPLE
    ./scripts/dev.ps1
#>

# 设置错误处理：遇到错误继续，但会报错（为了进程清理）
$ErrorActionPreference = "Continue"

Write-Host "`n🚀 正在启动 Pica Manga 开发环境..." -ForegroundColor Cyan

# ---------------------------------------------------------
# 1. 进程清理函数
# ---------------------------------------------------------
function Stop-PortProcess {
    param (
        [int]$Port,
        [string]$Name
    )
    
    $process = Get-NetTCPConnection -LocalPort $Port -ErrorAction SilentlyContinue | Select-Object -ExpandProperty OwningProcess -Unique
    if ($process) {
        Write-Host "   Creating clean slate... Killing process on port $Port ($Name)" -ForegroundColor Yellow
        Stop-Process -Id $process -Force -ErrorAction SilentlyContinue
    }
}

Write-Host "🧹 清理旧进程..." -ForegroundColor Green
Stop-PortProcess -Port 3000 -Name "Backend"
Stop-PortProcess -Port 5173 -Name "Frontend"

# ---------------------------------------------------------
# 2. 环境配置检查
# ---------------------------------------------------------
$EnvFile = Join-Path $PSScriptRoot "..\.env"
$ExampleFile = Join-Path $PSScriptRoot "..\.env.example"

if (-not (Test-Path $EnvFile)) {
    Write-Host "📝 .env 文件不存在，正在从模板创建..." -ForegroundColor Yellow
    Copy-Item $ExampleFile $EnvFile
    
    # 自动追加 HOST=0.0.0.0 (如果模板里没有)
    $EnvContent = Get-Content $EnvFile
    if ($EnvContent -notmatch "HOST=") {
        Add-Content -Path $EnvFile -Value "`n# Generated by dev script`nHOST=0.0.0.0"
    }
    Write-Host "✅ .env 文件已创建。" -ForegroundColor Green
} else {
    # 检查现有的 .env 是否配置了 Host
    $Content = Get-Content $EnvFile
    if ($Content -notmatch "HOST=0.0.0.0") {
         Write-Host "⚠️  提示: 建议在 .env 中设置 HOST=0.0.0.0 以允许局域网访问" -ForegroundColor DarkGray
    }
}

# ---------------------------------------------------------
# 3. 获取局域网 IP
# ---------------------------------------------------------
$IP = Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias "Wi-Fi","Ethernet","WLAN" -ErrorAction SilentlyContinue | 
      Where-Object { $_.IPAddress -like "192.168.*" -or $_.IPAddress -like "10.*" } | 
      Select-Object -ExpandProperty IPAddress -First 1

if (-not $IP) {
    # Fallback just in case
    $IP = "localhost"
}

# ---------------------------------------------------------
# 4. 启动服务
# ---------------------------------------------------------
Write-Host "`n✨ 环境准备就绪!" -ForegroundColor Green
Write-Host "   📱 局域网访问地址 (后端): http://$($IP):3000" -ForegroundColor Cyan
Write-Host "   🎨 局域网访问地址 (前端): http://$($IP):5173" -ForegroundColor Cyan
Write-Host "   ⌨️  正在启动服务 (Ctrl+C 停止)...`n" -ForegroundColor Gray

# 使用 pnpm start 启动
# 注意：前提是 package.json 中 start 脚本使用的是 concurrently
Set-Location -Path (Join-Path $PSScriptRoot "..")
pnpm start
